### PR TITLE
address many clippy lints

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Comment by ChillFish8** [comment]
On the topic of Clippy, maybe it's worth adding this as part of the CI checks?

**Comment by robjtede** [comment]
Yeah. Though I might suggest adding it after starting to handle some of the error cases. There's 4 or so more lints left that I did not address because they pointed to `if let Err(_)` or similar and I assume the plan is to use these constructs later.

**Comment by ChillFish8** [comment]
I think it's probably worth fixing all of them, if we don't use it now I think we should remove them and then if needed we can always add them back later.

**Comment by robjtede** [comment]
Added fmt and clippy to CI following we do it in actix repos so that lints are displayed inline with diffs. Also addressed the remaining lints as you suggested.

**Comment by ChillFish8** [comment]
Works for me!

**Pull request merged**
